services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["pnpm", "start:dev"]
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: memosphere-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: